export const EXPENSE = {
  FOOD: 'FOOD',
  CLOTHES: 'CLOTHES',
  TRANSPORT: 'TRANSPORT',
  EDUCATION: 'EDUCATION',
  TRAVEL: 'TRAVEL',
  HEALTH: 'HEALTH',
  ENTERTAINMENT: 'ENTERTAINMENT',
  COMMUNICATION: 'COMMUNICATION',
  OTHER: 'OTHER',
};

export const EXPENSE_LIST = [
  EXPENSE.FOOD,
  EXPENSE.CLOTHES,
  EXPENSE.TRANSPORT,
  EXPENSE.EDUCATION,
  EXPENSE.TRAVEL,
  EXPENSE.HEALTH,
  EXPENSE.ENTERTAINMENT,
  EXPENSE.COMMUNICATION,
  EXPENSE.OTHER,
];
