export const EXPENSE_TYPE = {
  FOOD: 'FOOD',
  CLOTHES: 'CLOTHES',
  TRANSPORT: 'TRANSPORT',
  EDUCATION: 'EDUCATION',
  TRAVEL: 'TRAVEL',
  HEALTH: 'HEALTH',
  ENTERTAINMENT: 'ENTERTAINMENT',
  COMMUNICATION: 'COMMUNICATION',
  OTHER: 'OTHER',
};

export const EXPENSE_TYPE_LIST = [
  EXPENSE_TYPE.FOOD,
  EXPENSE_TYPE.CLOTHES,
  EXPENSE_TYPE.TRANSPORT,
  EXPENSE_TYPE.EDUCATION,
  EXPENSE_TYPE.TRAVEL,
  EXPENSE_TYPE.HEALTH,
  EXPENSE_TYPE.ENTERTAINMENT,
  EXPENSE_TYPE.COMMUNICATION,
  EXPENSE_TYPE.OTHER,
];
